
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mysite_development

test:
  <<: *default
  database: mysite_test

production:
  <<: *default
  database: mysite_production
  username: mysite
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>

