
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mysite_development
  username: postgres
  password: postgres
  

test:
  <<: *default
  database: mysite_test
  username: postgres
  password: postgres
  
production:
  <<: *default
  database: mysite_production  
  url: <%= ENV['DATABASE_URL'] %>
  username: postgres
  password: postgres
  secret_key_base: JdDgc2dWK582bQ7ZBZdsBEZ8jmZlI9iZ+gEY0yI/FttB4t+FMy4d4d47d7nlhmtu3yG2BIh6KIlvgoKybRQ11awrTcIh9tnuvbUaHNz/RqAFoSW/dQ1NlNEYeuZxjw7gZFalM3fncRMcz4tdi3l+Akgc7s7WB9AvKEGppeDeS0r5OqUo7Y00u5E/cxzvl1dR6n+HTPdT6tBPSPmUxvcNV4na5dGRmSuVf1T3Xj5EHQtSmz+1yKZTeAdarNsWNg8QNSzQ/PWmWZu0xYObZGMbA89iYPqktsgVKSZXpZBQ39zoZx+VZT2Zx2ONQb2xYs1cMbDmLMBZDBhdP1g1dt4y02xkuA2WvvjY9oK2xxMTNGE5IRCWXAB0BOLKVIrk9cqMiO8qOyhDdCEiARCeePUwHFo53cQAPEMDDN7E--A7Vplvs32r+b3oCe--2xADjTea7IuWq+t8yilbaw==

